[window]

opacity = 0.5

[font]

normal = { family = "ProFont IIx Nerd Font", style = "Regular" }

bold = { family = "ProFont IIx Nerd Font",	style =	"Bold" }

italic = { family = "ProFont IIx Nerd Font",	style =	"Italic" }

bold_italic = { family = "ProFont IIx Nerd Font",	style =	"BoldItalic" }

size = 9.4

offset = { x = 0, y = 0 }

glyph_offset = { x = 0, y = 0 }
